-- ============================================================
-- ICT371 Activity 4 - Scenario 3: Hostel Room Allocation
-- Student Number: 202400550
-- ============================================================

DROP SCHEMA IF EXISTS scenario3_hostel CASCADE;
CREATE SCHEMA scenario3_hostel;
SET search_path TO scenario3_hostel, public;

-- ------------------------------------------------------------
-- Step 1: Create tables and add at least three rooms
-- ------------------------------------------------------------
CREATE TABLE hostel_rooms (
    room_id integer PRIMARY KEY,
    room_name text NOT NULL,
    available_spaces integer NOT NULL CHECK (available_spaces >= 0)
);

CREATE TABLE allocations (
    allocation_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id integer NOT NULL REFERENCES hostel_rooms(room_id),
    student_number text NOT NULL,
    status text NOT NULL CHECK (status IN ('ACTIVE', 'COMPLETED'))
);

INSERT INTO hostel_rooms (room_id, room_name, available_spaces)
VALUES (1, 'Block A - Room 101', 5),
       (2, 'Block B - Room 202', 1),
       (3, 'Block C - Room 303', 0);

SELECT * FROM hostel_rooms ORDER BY room_id;

-- ------------------------------------------------------------
-- Step 2: IF ELSIF ELSE - report room status
-- ------------------------------------------------------------
DO $$
DECLARE
    v_spaces integer;
BEGIN
    SELECT available_spaces INTO v_spaces
    FROM hostel_rooms WHERE room_id = 2;

    IF v_spaces = 0 THEN
        RAISE NOTICE 'Room 2 is full';
    ELSIF v_spaces = 1 THEN
        RAISE NOTICE 'Room 2 has one space left';
    ELSE
        RAISE NOTICE 'Room 2 has several spaces: %', v_spaces;
    END IF;
END $$ LANGUAGE plpgsql;

-- ------------------------------------------------------------
-- Step 3: WHILE and numeric FOR loops
-- ------------------------------------------------------------
DO $$
DECLARE
    v_counter integer := 1;
BEGIN
    WHILE v_counter <= 3 LOOP
        RAISE NOTICE 'Hostel inspection day: %', v_counter;
        v_counter := v_counter + 1;
    END LOOP;

    FOR i IN 1..3 LOOP
        RAISE NOTICE 'Room check number: %', i;
    END LOOP;
END $$ LANGUAGE plpgsql;

-- ------------------------------------------------------------
-- Step 4: Create allocate_room procedure
-- ------------------------------------------------------------
CREATE OR REPLACE PROCEDURE allocate_room(
    p_room_id integer,
    p_student_number text
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_available integer;
    v_allocation_id integer;
BEGIN
    IF p_student_number IS NULL OR TRIM(p_student_number) = '' THEN
        RAISE EXCEPTION 'Student number cannot be blank'
        USING ERRCODE = '22023';
    END IF;

    SELECT available_spaces INTO v_available
    FROM hostel_rooms WHERE room_id = p_room_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE NOTICE 'Room % does not exist', p_room_id;
        RETURN;
    ELSIF v_available < 1 THEN
        RAISE NOTICE 'Room % is full', p_room_id;
        RETURN;
    END IF;

    UPDATE hostel_rooms
    SET available_spaces = available_spaces - 1
    WHERE room_id = p_room_id;

    INSERT INTO allocations (room_id, student_number, status)
    VALUES (p_room_id, p_student_number, 'ACTIVE')
    RETURNING allocation_id INTO v_allocation_id;

    RAISE NOTICE 'Allocation % created for student %',
        v_allocation_id, p_student_number;
END;
$$;

-- ------------------------------------------------------------
-- Step 5: Call it - 2 valid, 1 to a full room
-- ------------------------------------------------------------
CALL allocate_room(1, 'STU001');
CALL allocate_room(2, 'STU002');
CALL allocate_room(3, 'STU003');

SELECT * FROM hostel_rooms ORDER BY room_id;
SELECT allocation_id, room_id, student_number, status
FROM allocations ORDER BY allocation_id;

-- ------------------------------------------------------------
-- Step 6: Create check_out procedure
-- ------------------------------------------------------------
CREATE OR REPLACE PROCEDURE check_out(p_allocation_id integer)
LANGUAGE plpgsql
AS $$
DECLARE
    v_room_id integer;
BEGIN
    SELECT room_id INTO v_room_id
    FROM allocations
    WHERE allocation_id = p_allocation_id AND status = 'ACTIVE'
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE NOTICE 'No active allocation with ID %', p_allocation_id;
        RETURN;
    END IF;

    UPDATE allocations
    SET status = 'COMPLETED'
    WHERE allocation_id = p_allocation_id;

    UPDATE hostel_rooms
    SET available_spaces = available_spaces + 1
    WHERE room_id = v_room_id;

    RAISE NOTICE 'Allocation % completed; 1 space released', p_allocation_id;
END;
$$;

CALL check_out(1);
CALL check_out(1);

SELECT * FROM hostel_rooms ORDER BY room_id;
SELECT allocation_id, status FROM allocations ORDER BY allocation_id;

-- ------------------------------------------------------------
-- Step 7: Explicit cursor - full or nearly full rooms
-- ------------------------------------------------------------
CREATE OR REPLACE PROCEDURE show_full_or_nearly_full()
LANGUAGE plpgsql
AS $$
DECLARE
    v_item record;
    c_low CURSOR FOR
        SELECT room_name, available_spaces
        FROM hostel_rooms
        WHERE available_spaces <= 1
        ORDER BY room_id;
BEGIN
    OPEN c_low;
    LOOP
        FETCH c_low INTO v_item;
        EXIT WHEN NOT FOUND;
        RAISE NOTICE 'Full/nearly full: % (% spaces left)',
            v_item.room_name, v_item.available_spaces;
    END LOOP;
    CLOSE c_low;
END;
$$;

CALL show_full_or_nearly_full();

-- ------------------------------------------------------------
-- Step 8: Blank student number + handle exception
-- ------------------------------------------------------------
DO $$
BEGIN
    CALL allocate_room(1, '');
EXCEPTION
    WHEN invalid_parameter_value THEN
        RAISE NOTICE 'Handled expected error: %', SQLERRM;
END $$ LANGUAGE plpgsql;

-- ------------------------------------------------------------
-- Step 9: Final state
-- ------------------------------------------------------------
SELECT * FROM hostel_rooms ORDER BY room_id;
SELECT allocation_id, room_id, student_number, status
FROM allocations ORDER BY allocation_id;