-- ============================================================
-- ICT371 Activity 4 - Scenario 4: Campus Clinic Medicine Dispensing
-- Student Name: Evans Saikolo
-- Student Number: 202400550
-- ============================================================

DROP SCHEMA IF EXISTS scenario4_clinic CASCADE;
CREATE SCHEMA scenario4_clinic;
SET search_path TO scenario4_clinic, public;

-- ------------------------------------------------------------
-- Step 1: Create tables and add at least three medicines
-- ------------------------------------------------------------
CREATE TABLE medicines (
    medicine_id integer PRIMARY KEY,
    medicine_name text NOT NULL,
    stock_quantity integer NOT NULL CHECK (stock_quantity >= 0)
);

CREATE TABLE dispensing_records (
    record_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medicine_id integer NOT NULL REFERENCES medicines(medicine_id),
    student_number text NOT NULL,
    quantity integer NOT NULL,
    status text NOT NULL CHECK (status IN ('DISPENSED', 'REVERSED'))
);

INSERT INTO medicines (medicine_id, medicine_name, stock_quantity)
VALUES (1, 'Paracetamol', 50),
       (2, 'Amoxicillin', 8),
       (3, 'Cough Syrup', 0);

SELECT * FROM medicines ORDER BY medicine_id;

-- ------------------------------------------------------------
-- Step 2: IF ELSIF ELSE - report stock status
-- ------------------------------------------------------------
DO $$
DECLARE
    v_stock integer;
BEGIN
    SELECT stock_quantity INTO v_stock
    FROM medicines WHERE medicine_id = 2;

    IF v_stock = 0 THEN
        RAISE NOTICE 'Medicine 2 is out of stock';
    ELSIF v_stock <= 10 THEN
        RAISE NOTICE 'Medicine 2 is low on stock: % remaining', v_stock;
    ELSE
        RAISE NOTICE 'Medicine 2 is sufficiently stocked: %', v_stock;
    END IF;
END $$ LANGUAGE plpgsql;

-- ------------------------------------------------------------
-- Step 3: WHILE and numeric FOR loops
-- ------------------------------------------------------------
DO $$
DECLARE
    v_counter integer := 1;
BEGIN
    WHILE v_counter <= 3 LOOP
        RAISE NOTICE 'Stock review day: %', v_counter;
        v_counter := v_counter + 1;
    END LOOP;

    FOR i IN 1..3 LOOP
        RAISE NOTICE 'Shelf inspection number: %', i;
    END LOOP;
END $$ LANGUAGE plpgsql;

-- ------------------------------------------------------------
-- Step 4: Create dispense_medicine procedure
-- ------------------------------------------------------------
CREATE OR REPLACE PROCEDURE dispense_medicine(
    p_medicine_id integer,
    p_student_number text,
    p_quantity integer
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_stock integer;
    v_record_id integer;
BEGIN
    IF p_quantity <= 0 THEN
        RAISE EXCEPTION 'Dispensing quantity must be positive'
        USING ERRCODE = '22023';
    END IF;

    SELECT stock_quantity INTO v_stock
    FROM medicines WHERE medicine_id = p_medicine_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE NOTICE 'Medicine % does not exist', p_medicine_id;
        RETURN;
    ELSIF v_stock < p_quantity THEN
        RAISE NOTICE 'Insufficient stock: only % available', v_stock;
        RETURN;
    END IF;

    UPDATE medicines
    SET stock_quantity = stock_quantity - p_quantity
    WHERE medicine_id = p_medicine_id;

    INSERT INTO dispensing_records (medicine_id, student_number, quantity, status)
    VALUES (p_medicine_id, p_student_number, p_quantity, 'DISPENSED')
    RETURNING record_id INTO v_record_id;

    RAISE NOTICE 'Dispensing record % created for student %',
        v_record_id, p_student_number;
END;
$$;

-- ------------------------------------------------------------
-- Step 5: Call it - 2 valid, 1 exceeding stock
-- ------------------------------------------------------------
CALL dispense_medicine(1, 'STU001', 10);
CALL dispense_medicine(2, 'STU002', 5);
CALL dispense_medicine(2, 'STU003', 100);

SELECT * FROM medicines ORDER BY medicine_id;
SELECT record_id, medicine_id, student_number, quantity, status
FROM dispensing_records ORDER BY record_id;

-- ------------------------------------------------------------
-- Step 6: Create reverse_dispensing procedure
-- ------------------------------------------------------------
CREATE OR REPLACE PROCEDURE reverse_dispensing(p_record_id integer)
LANGUAGE plpgsql
AS $$
DECLARE
    v_medicine_id integer;
    v_quantity integer;
BEGIN
    SELECT medicine_id, quantity
    INTO v_medicine_id, v_quantity
    FROM dispensing_records
    WHERE record_id = p_record_id AND status = 'DISPENSED'
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE NOTICE 'No active dispensing record with ID %', p_record_id;
        RETURN;
    END IF;

    UPDATE dispensing_records
    SET status = 'REVERSED'
    WHERE record_id = p_record_id;

    UPDATE medicines
    SET stock_quantity = stock_quantity + v_quantity
    WHERE medicine_id = v_medicine_id;

    RAISE NOTICE 'Record % reversed; % units restored',
        p_record_id, v_quantity;
END;
$$;

CALL reverse_dispensing(1);
CALL reverse_dispensing(1);

SELECT * FROM medicines ORDER BY medicine_id;
SELECT record_id, status FROM dispensing_records ORDER BY record_id;

-- ------------------------------------------------------------
-- Step 7: Explicit cursor - low-stock medicines (below threshold)
-- ------------------------------------------------------------
CREATE OR REPLACE PROCEDURE show_low_stock_medicines()
LANGUAGE plpgsql
AS $$
DECLARE
    v_item record;
    c_low CURSOR FOR
        SELECT medicine_name, stock_quantity
        FROM medicines
        WHERE stock_quantity <= 10
        ORDER BY medicine_id;
BEGIN
    OPEN c_low;
    LOOP
        FETCH c_low INTO v_item;
        EXIT WHEN NOT FOUND;
        RAISE NOTICE 'Low stock: % (% units)', v_item.medicine_name, v_item.stock_quantity;
    END LOOP;
    CLOSE c_low;
END;
$$;

CALL show_low_stock_medicines();

-- ------------------------------------------------------------
-- Step 8: Negative dispensing quantity + handle exception
-- ------------------------------------------------------------
DO $$
BEGIN
    CALL dispense_medicine(3, 'STU004', -5);
EXCEPTION
    WHEN invalid_parameter_value THEN
        RAISE NOTICE 'Handled expected error: %', SQLERRM;
END $$ LANGUAGE plpgsql;

-- ------------------------------------------------------------
-- Step 9: Final state
-- ------------------------------------------------------------
SELECT * FROM medicines ORDER BY medicine_id;
SELECT record_id, medicine_id, student_number, quantity, status
FROM dispensing_records ORDER BY record_id;