-- ============================================================
-- ICT371 Activity 4 - Scenario 1: Library Book Loans
-- Student Name: Evans Saikolo
-- Student Number: 202400550
-- ============================================================

DROP SCHEMA IF EXISTS scenario1_lib CASCADE;
CREATE SCHEMA scenario1_lib;
SET search_path TO scenario1_lib, public;

-- ------------------------------------------------------------
-- Step 1: Create tables and add at least three books
-- ------------------------------------------------------------
CREATE TABLE books (
    book_id integer PRIMARY KEY,
    title text NOT NULL,
    available_copies integer NOT NULL CHECK (available_copies >= 0)
);

CREATE TABLE book_loans (
    loan_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id integer NOT NULL REFERENCES books(book_id),
    student_number text NOT NULL,
    quantity integer NOT NULL CHECK (quantity > 0),
    status text NOT NULL CHECK (status IN ('ACTIVE', 'RETURNED'))
);

INSERT INTO books (book_id, title, available_copies)
VALUES (1, 'Introduction to Databases', 5),
       (2, 'Advanced SQL', 2),
       (3, 'Python Programming', 0);

SELECT * FROM books ORDER BY book_id;

-- ------------------------------------------------------------
-- Step 2: IF ELSIF ELSE - display stock status of book 2
-- ------------------------------------------------------------
DO $$
DECLARE
    v_copies integer;
BEGIN
    SELECT available_copies INTO v_copies
    FROM books WHERE book_id = 2;

    IF v_copies = 0 THEN
        RAISE NOTICE 'Book 2 is unavailable';
    ELSIF v_copies <= 2 THEN
        RAISE NOTICE 'Book 2 is low on copies: % remaining', v_copies;
    ELSE
        RAISE NOTICE 'Book 2 is sufficiently stocked: % copies', v_copies;
    END IF;
END $$ LANGUAGE plpgsql;

-- ------------------------------------------------------------
-- Step 3: WHILE and numeric FOR loops
-- ------------------------------------------------------------
DO $$
DECLARE
    v_counter integer := 1;
BEGIN
    WHILE v_counter <= 3 LOOP
        RAISE NOTICE 'Overdue reminder number: %', v_counter;
        v_counter := v_counter + 1;
    END LOOP;

    FOR i IN 1..3 LOOP
        RAISE NOTICE 'Library shelf number: %', i;
    END LOOP;
END $$ LANGUAGE plpgsql;

-- ------------------------------------------------------------
-- Step 4: Create borrow_book procedure
-- ------------------------------------------------------------
CREATE OR REPLACE PROCEDURE borrow_book(
    p_book_id integer,
    p_student_number text,
    p_quantity integer
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_available integer;
    v_loan_id integer;
BEGIN
    IF p_quantity <= 0 THEN
        RAISE EXCEPTION 'Quantity must be positive'
        USING ERRCODE = '22023';
    END IF;

    SELECT available_copies INTO v_available
    FROM books WHERE book_id = p_book_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE NOTICE 'Book % does not exist', p_book_id;
        RETURN;
    ELSIF v_available < p_quantity THEN
        RAISE NOTICE 'Insufficient copies: only % available', v_available;
        RETURN;
    END IF;

    UPDATE books
    SET available_copies = available_copies - p_quantity
    WHERE book_id = p_book_id;

    INSERT INTO book_loans (book_id, student_number, quantity, status)
    VALUES (p_book_id, p_student_number, p_quantity, 'ACTIVE')
    RETURNING loan_id INTO v_loan_id;

    RAISE NOTICE 'Loan % created for student %', v_loan_id, p_student_number;
END;
$$;

-- ------------------------------------------------------------
-- Step 5: Call borrow_book - 2 valid, 1 exceeding
-- ------------------------------------------------------------
CALL borrow_book(1, 'STU001', 2);
CALL borrow_book(2, 'STU002', 1);
CALL borrow_book(2, 'STU003', 10);

SELECT * FROM books ORDER BY book_id;
SELECT loan_id, book_id, student_number, quantity, status
FROM book_loans ORDER BY loan_id;

-- ------------------------------------------------------------
-- Step 6: Create return_book procedure
-- ------------------------------------------------------------
CREATE OR REPLACE PROCEDURE return_book(p_loan_id integer)
LANGUAGE plpgsql
AS $$
DECLARE
    v_book_id integer;
    v_quantity integer;
BEGIN
    SELECT book_id, quantity
    INTO v_book_id, v_quantity
    FROM book_loans
    WHERE loan_id = p_loan_id AND status = 'ACTIVE'
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE NOTICE 'No active loan with ID %', p_loan_id;
        RETURN;
    END IF;

    UPDATE book_loans
    SET status = 'RETURNED' WHERE loan_id = p_loan_id;

    UPDATE books
    SET available_copies = available_copies + v_quantity
    WHERE book_id = v_book_id;

    RAISE NOTICE 'Loan % returned; % copies restored', p_loan_id, v_quantity;
END;
$$;

CALL return_book(1);
CALL return_book(1);

SELECT * FROM books ORDER BY book_id;
SELECT loan_id, status FROM book_loans ORDER BY loan_id;

-- ------------------------------------------------------------
-- Step 7: Explicit cursor - low-stock books
-- ------------------------------------------------------------
CREATE OR REPLACE PROCEDURE show_low_stock_books()
LANGUAGE plpgsql
AS $$
DECLARE
    v_item record;
    c_low CURSOR FOR
        SELECT title, available_copies
        FROM books
        WHERE available_copies <= 2
        ORDER BY book_id;
BEGIN
    OPEN c_low;
    LOOP
        FETCH c_low INTO v_item;
        EXIT WHEN NOT FOUND;
        RAISE NOTICE 'Low stock: % (% copies)', v_item.title, v_item.available_copies;
    END LOOP;
    CLOSE c_low;
END;
$$;

CALL show_low_stock_books();

-- ------------------------------------------------------------
-- Step 8: Try to borrow zero copies + handle exception
-- ------------------------------------------------------------
DO $$
BEGIN
    CALL borrow_book(3, 'STU004', 0);
EXCEPTION
    WHEN invalid_parameter_value THEN
        RAISE NOTICE 'Handled expected error: %', SQLERRM;
END $$ LANGUAGE plpgsql;

-- ------------------------------------------------------------
-- Step 9: Final state
-- ------------------------------------------------------------
SELECT * FROM books ORDER BY book_id;
SELECT loan_id, book_id, student_number, quantity, status
FROM book_loans ORDER BY loan_id;