-- ============================================================
-- ICT371 Activity 4 - Scenario 2: Computer Laboratory Reservations
-- Student Name: Evans Saikolo
-- Student Number: 202400550
-- ============================================================

DROP SCHEMA IF EXISTS scenario2_lab CASCADE;
CREATE SCHEMA scenario2_lab;
SET search_path TO scenario2_lab, public;

-- ------------------------------------------------------------
-- Step 1: Create tables and add at least three sessions
-- ------------------------------------------------------------
CREATE TABLE lab_sessions (
    session_id integer PRIMARY KEY,
    session_name text NOT NULL,
    available_workstations integer NOT NULL CHECK (available_workstations >= 0)
);

CREATE TABLE reservations (
    reservation_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id integer NOT NULL REFERENCES lab_sessions(session_id),
    lecturer_name text NOT NULL,
    workstations integer NOT NULL CHECK (workstations > 0),
    status text NOT NULL CHECK (status IN ('ACTIVE', 'CANCELLED'))
);

INSERT INTO lab_sessions (session_id, session_name, available_workstations)
VALUES (1, 'Monday Morning Lab', 20),
       (2, 'Wednesday Afternoon Lab', 3),
       (3, 'Friday Evening Lab', 0);

SELECT * FROM lab_sessions ORDER BY session_id;

-- ------------------------------------------------------------
-- Step 2: IF ELSIF ELSE - report session status
-- ------------------------------------------------------------
DO $$
DECLARE
    v_ws integer;
BEGIN
    SELECT available_workstations INTO v_ws
    FROM lab_sessions WHERE session_id = 2;

    IF v_ws = 0 THEN
        RAISE NOTICE 'Session 2 is full';
    ELSIF v_ws <= 5 THEN
        RAISE NOTICE 'Session 2 is nearly full: % workstations left', v_ws;
    ELSE
        RAISE NOTICE 'Session 2 has enough workstations: %', v_ws;
    END IF;
END $$ LANGUAGE plpgsql;

-- ------------------------------------------------------------
-- Step 3: WHILE and numeric FOR loops
-- ------------------------------------------------------------
DO $$
DECLARE
    v_counter integer := 1;
BEGIN
    WHILE v_counter <= 3 LOOP
        RAISE NOTICE 'Session preparation reminder: %', v_counter;
        v_counter := v_counter + 1;
    END LOOP;

    FOR i IN 1..3 LOOP
        RAISE NOTICE 'Workstation check number: %', i;
    END LOOP;
END $$ LANGUAGE plpgsql;

-- ------------------------------------------------------------
-- Step 4: Create reserve_workstations procedure
-- ------------------------------------------------------------
CREATE OR REPLACE PROCEDURE reserve_workstations(
    p_session_id integer,
    p_lecturer text,
    p_workstations integer
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_available integer;
    v_reservation_id integer;
BEGIN
    IF p_workstations <= 0 THEN
        RAISE EXCEPTION 'Number of workstations must be positive'
        USING ERRCODE = '22023';
    END IF;

    SELECT available_workstations INTO v_available
    FROM lab_sessions WHERE session_id = p_session_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE NOTICE 'Session % does not exist', p_session_id;
        RETURN;
    ELSIF v_available < p_workstations THEN
        RAISE NOTICE 'Insufficient workstations: only % available', v_available;
        RETURN;
    END IF;

    UPDATE lab_sessions
    SET available_workstations = available_workstations - p_workstations
    WHERE session_id = p_session_id;

    INSERT INTO reservations (session_id, lecturer_name, workstations, status)
    VALUES (p_session_id, p_lecturer, p_workstations, 'ACTIVE')
    RETURNING reservation_id INTO v_reservation_id;

    RAISE NOTICE 'Reservation % created for lecturer %',
        v_reservation_id, p_lecturer;
END;
$$;

-- ------------------------------------------------------------
-- Step 5: Call it - 2 valid, 1 exceeding
-- ------------------------------------------------------------
CALL reserve_workstations(1, 'Dr. Banda', 5);
CALL reserve_workstations(2, 'Prof. Mulenga', 2);
CALL reserve_workstations(2, 'Dr. Zulu', 10);

SELECT * FROM lab_sessions ORDER BY session_id;
SELECT reservation_id, session_id, lecturer_name, workstations, status
FROM reservations ORDER BY reservation_id;

-- ------------------------------------------------------------
-- Step 6: Create cancel_reservation procedure
-- ------------------------------------------------------------
CREATE OR REPLACE PROCEDURE cancel_reservation(p_reservation_id integer)
LANGUAGE plpgsql
AS $$
DECLARE
    v_session_id integer;
    v_workstations integer;
BEGIN
    SELECT session_id, workstations
    INTO v_session_id, v_workstations
    FROM reservations
    WHERE reservation_id = p_reservation_id AND status = 'ACTIVE'
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE NOTICE 'No active reservation with ID %', p_reservation_id;
        RETURN;
    END IF;

    UPDATE reservations
    SET status = 'CANCELLED'
    WHERE reservation_id = p_reservation_id;

    UPDATE lab_sessions
    SET available_workstations = available_workstations + v_workstations
    WHERE session_id = v_session_id;

    RAISE NOTICE 'Reservation % cancelled; % workstations released',
        p_reservation_id, v_workstations;
END;
$$;

CALL cancel_reservation(1);
CALL cancel_reservation(1);

SELECT * FROM lab_sessions ORDER BY session_id;
SELECT reservation_id, status FROM reservations ORDER BY reservation_id;

-- ------------------------------------------------------------
-- Step 7: Explicit cursor - sessions with few workstations
-- ------------------------------------------------------------
CREATE OR REPLACE PROCEDURE show_low_availability()
LANGUAGE plpgsql
AS $$
DECLARE
    v_item record;
    c_low CURSOR FOR
        SELECT session_name, available_workstations
        FROM lab_sessions
        WHERE available_workstations <= 5
        ORDER BY session_id;
BEGIN
    OPEN c_low;
    LOOP
        FETCH c_low INTO v_item;
        EXIT WHEN NOT FOUND;
        RAISE NOTICE 'Low availability: % (% left)',
            v_item.session_name, v_item.available_workstations;
    END LOOP;
    CLOSE c_low;
END;
$$;

CALL show_low_availability();

-- ------------------------------------------------------------
-- Step 8: Request zero workstations + handle exception
-- ------------------------------------------------------------
DO $$
BEGIN
    CALL reserve_workstations(3, 'Dr. Phiri', 0);
EXCEPTION
    WHEN invalid_parameter_value THEN
        RAISE NOTICE 'Handled expected error: %', SQLERRM;
END $$ LANGUAGE plpgsql;

-- ------------------------------------------------------------
-- Step 9: Final state
-- ------------------------------------------------------------
SELECT * FROM lab_sessions ORDER BY session_id;
SELECT reservation_id, session_id, lecturer_name, workstations, status
FROM reservations ORDER BY reservation_id;